apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aipp

labels:
  - pairs:
      app.kubernetes.io/part-of: aipp
      app.kubernetes.io/managed-by: argocd

resources:
  - namespace.yaml
  - secrets.yaml
  - pgvector.yaml
  - redis.yaml
  - rabbitmq.yaml
  - backend.yaml
  - data-processor.yaml
  - scheduler.yaml
  - frontend.yaml
  - linker.yaml
